version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: flask-app
    volumes:
      - ./backend/app/static:/app/static
      - ./frontend:/app/frontend
    ports:
      - "5000:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: celery-worker
    command: celery -A celery_config.celery worker --loglevel=info
    working_dir: /app
    volumes:
      - ./backend/app/static:/app/static
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  beat:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: celery-beat
    command: celery -A celery_config.celery beat --loglevel=info
    working_dir: /app
    volumes:
      - ./backend/app/static:/app/static
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
